defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true

development:
  sessions:
    default:
      <<: *defaults
      database: hoosCron_development
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      <<: *defaults
      uri: <%= ENV['MONGOHQ_URL'] %>